export const allowTag = [
  "Minimalism Style",
  "Bamboo Material",
  "Curved  Ribs Dome Framework",
  "Grid Dome Framework",
  "Geodesic Dome Framework",
  "Hexagonal Dome Framework",
  "Fence",
  "Forest",
  "Garden",
  "Grass",
  "Hemispherical Design",
  "Mountain Environment",
  "Nature",
  "Outdoors",
  "Polygonal Grid",
  "Scenery",
  "Self-Supporting Structure",
  "Sky",
  "Sunlight",
  "Tree",
];
